on:
  workflow_dispatch:
env:
  cat_name: "Puszek"
  WORKFLOW_VAR: "Zmienna w scopie workflow"

jobs:
  display-variables:
    name: ${{vars.ENVIRONMENT_VAR}}
    env:
      JOB_VAR: "Zmienna w scopie joba"
    runs-on: ubuntu-latest
    steps:
      - name: Use variables 1
        run: |
          echo "Repository variable : $REPOSITORY_VAR"
          echo "Organization variable : $ORGANIZATION_VAR"
          echo "Environment variable : $ENVIRONMENT_VAR"
          echo "Ala ma kota o nazwie $cat_name"
          echo "Powinna być zmienna w scopie workflow:$WORKFLOW_VAR"
          echo "Powinna być zmienna w scopie joba:$JOB_VAR"
          echo "Powinna być zmienna w scopie stepu:$STEP_VAR"
        env:
          REPOSITORY_VAR: ${{vars.REPOSITORY_VAR}}
          ORGANIZATION_VAR: ${{vars.ORGANIZATION_VAR}}
          ENVIRONMENT_VAR: ${{vars.ENVIRONMENT_VAR}}
          STEP_VAR: "Zmienna w scopie stepu 1"

      - name: Use variables 2
        run: |
          echo "Ala ma kota o nazwie $cat_name"
          echo "Powinna być zmienna w scopie workflow:$WORKFLOW_VAR"
          echo "Powinna być zmienna w scopie joba:$JOB_VAR"
          echo "NIE powinna być zmienna w scopie stepu:$STEP_VAR"
        env:
          STEP_VAR: "Zmienna w scopie stepu 2"
          REPOSITORY_VAR: ${{vars.REPOSITORY_VAR}}
          ORGANIZATION_VAR: ${{vars.ORGANIZATION_VAR}}
          ENVIRONMENT_VAR: ${{vars.ENVIRONMENT_VAR}}

  display-variables2:
    runs-on: ubuntu-latest
    steps:
      - name: Use variables in display-variables2
        run: |
          echo "Powinna być zmienna w scopie workflow:$WORKFLOW_VAR"
          echo "NIE powinna być zmienna w scopie joba:$JOB_VAR"
          echo "NIE powinna być zmienna w scopie stepu:$STEP_VAR"
        env:
          STEP_VAR: "Zmienna w scopie stepu 3"
